# Section A - Exception Handling

In [1]:
"""
1. Write a function safe_divide(a, b) that divides two numbers and handles 
ZeroDivisionError and TypeError separately, printing an appropriate message for each. 
Use a finally block to print 'Operation attempted.' regardless of the outcome.
Test it with valid numbers, division by zero, and a string input.
""";

In [2]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except TypeError:
        print("Error: Both inputs must be numbers.")

    finally:
        print("Operation attempted.")

# Test Cases

print("Test 1: Valid Division")
safe_divide(20, 5)

print("\nTest 2: Division by Zero")
safe_divide(10, 0)

print("\nTest 3: String Input")
safe_divide("20", 5)

Test 1: Valid Division
Result: 4.0
Operation attempted.

Test 2: Division by Zero
Error: Cannot divide by zero.
Operation attempted.

Test 3: String Input
Error: Both inputs must be numbers.
Operation attempted.


In [3]:
"""
2. Write a function validate_age(age) that raises a custom exception InvalidAgeError 
(a class you define, inheriting from Exception) if age is negative or greater than 120. 
Catch this exception in a calling block and print a user-friendly message.
Test it with at least 3 different values.
""";

In [4]:
# Custom Exception
class InvalidAgeError(Exception):
    pass

# Function to validate age
def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Age must be between 0 and 120.")
    else:
        print("Valid age:", age)

# Test Cases
ages = [25, -5, 150]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Invalid Age Error:", e)

Valid age: 25
Invalid Age Error: Age must be between 0 and 120.
Invalid Age Error: Age must be between 0 and 120.


In [5]:
"""
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list, e.g.
user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. 
Handle the following in a single try block using multiple except clauses:

a) ValueError if the input is not a number.

b) ZeroDivisionError if the input is zero.

c) A generic Exception as a catch-all for anything else.

Print the result if successful, otherwise print which error occurred.
""";

In [6]:
# Simulated user inputs
user_inputs = ['10', 'abc', '0', '5']

for user_input in user_inputs:
    print("Input:", user_input)

    try:
        num = int(user_input)
        result = 100 / num
        print("Result:", result)

    except ValueError:
        print("Error: Invalid number entered.")

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except Exception as e:
        print("Unexpected Error:", e)

    print()

Input: 10
Result: 10.0

Input: abc
Error: Invalid number entered.

Input: 0
Error: Cannot divide by zero.

Input: 5
Result: 20.0



# Section B - Numpy

In [7]:
"""
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:

a) Reshape it into a 4x5 2D array.

b) Print the sum of each row and each column.

c) Extract all elements greater than 10 using boolean indexing.

d) Replace all even numbers in the array with -1.
""";

In [8]:
import numpy as np

# Create a 1D array from 1 to 20
arr = np.arange(1, 21)

print("Original 1D Array:")
print(arr)

# a) Reshape into 4x5 array
arr2 = arr.reshape(4, 5)
print("\n4x5 Array:")
print(arr2)

# b) Sum of each row and each column
print("\nSum of each row:")
print(arr2.sum(axis=1))

print("\nSum of each column:")
print(arr2.sum(axis=0))

# c) Elements greater than 10
print("\nElements greater than 10:")
print(arr2[arr2 > 10])

# d) Replace all even numbers with -1
arr2[arr2 % 2 == 0] = -1

print("\nArray after replacing even numbers with -1:")
print(arr2)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of each row:
[15 40 65 90]

Sum of each column:
[34 38 42 46 50]

Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20]

Array after replacing even numbers with -1:
[[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [9]:
"""
5. Create two NumPy arrays A and B as shown below and perform:

Anp.array([[1, 2], [3, 4]]) B= np.array([[5, 6], [7, 8]])

a) Element-wise addition, subtraction, and multiplication.

b) Matrix multiplication using np.dot() or the @ operator.

c) Transpose of A.

d) The determinant and inverse of A using np.linalg.
""";

In [10]:
import numpy as np

# Create arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# a) Element-wise operations
print("\nElement-wise Addition:")
print(A + B)

print("\nElement-wise Subtraction:")
print(A - B)

print("\nElement-wise Multiplication:")
print(A * B)

# b) Matrix Multiplication
print("\nMatrix Multiplication (A @ B):")
print(np.dot(A, B))
# or print(A @ B)

# c) Transpose of A
print("\nTranspose of A:")
print(A.T)

# d) Determinant and Inverse of A
print("\nDeterminant of A:")
print(np.linalg.det(A))

print("\nInverse of A:")
print(np.linalg.inv(A))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
"""
6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint() 
(set a seed of 42 for reproducibility). Then:

a) Find the mean, median, standard deviation, min, and max.

b) Sort the array in descending order.

c) Find the indices of the 3 largest values using np.argsort().

d) Normalize the array so all values lie between 0 and 1.
""";

In [12]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate 15 random integers between 1 and 100
arr = np.random.randint(1, 101, 15)

print("Original Array:")
print(arr)

# a) Mean, Median, Standard Deviation, Min, Max
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# b) Sort the array in descending order
sorted_arr = np.sort(arr)[::-1]
print("\nArray in Descending Order:")
print(sorted_arr)

# c) Indices of the 3 largest values
indices = np.argsort(arr)[-3:][::-1]
print("\nIndices of the 3 Largest Values:")
print(indices)

# d) Normalize the array between 0 and 1
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("\nNormalized Array:")
print(normalized)

Original Array:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100

Array in Descending Order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of the 3 Largest Values:
[11  1 10]

Normalized Array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


# Section C - Pandas Basics

In [13]:
"""
7. Create a Pandas DataFrame from the dictionary below and perform the following:

data {"Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21, 25, 22, 24], "Department":
["AI", "Data Science", "AI", "Web Dev", "Data Science"], "Score": [88, 92, 79, 95, 67], }

a) Display the first 3 rows and the data types of each column.

b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').

c) Sort the DataFrame by Score in descending order.

d) Filter rows where Department is 'Al'.
""";

In [14]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) Display first 3 rows and data types
print("First 3 Rows:")
print(df.head(3))

print("\nData Types:")
print(df.dtypes)

# b) Add Grade column
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 75:
        return "B"
    else:
        return "C"

df["Grade"] = df["Score"].apply(grade)

print("\nDataFrame with Grade:")
print(df)

# c) Sort by Score in descending order
sorted_df = df.sort_values(by="Score", ascending=False)

print("\nSorted by Score (Descending):")
print(sorted_df)

# d) Filter rows where Department is 'AI'
ai_df = df[df["Department"] == "AI"]

print("\nStudents in AI Department:")
print(ai_df)

First 3 Rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (Descending):
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Students in AI Department:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [15]:
"""
8. Using the same DataFrame from Q7:

a) Group by Department and find the average Score for each.

b) Find the row with the highest Score using idxmax().

c) Rename the column Score to Marks.

d) Drop the Age column and display the resulting DataFrame.
""";

In [16]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) Group by Department and find average Score
print("Average Score by Department:")
print(df.groupby("Department")["Score"].mean())

# b) Find the row with the highest Score using idxmax()
print("\nStudent with Highest Score:")
print(df.loc[df["Score"].idxmax()])

# c) Rename 'Score' column to 'Marks'
df = df.rename(columns={"Score": "Marks"})
print("\nDataFrame after Renaming:")
print(df)

# d) Drop the Age column
df = df.drop(columns=["Age"])
print("\nDataFrame after Dropping Age:")
print(df)

Average Score by Department:
Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Student with Highest Score:
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

DataFrame after Renaming:
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

DataFrame after Dropping Age:
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [17]:
"""
9. Create a DataFrame with some missing values as shown below and handle them:

import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
"Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50, np.nan, 30, 20], )

a) Check the number of missing values in each column using isnull().sum().

b) Fill missing Price values with the column mean.

c) Drop rows where Stock is still missing.

d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.
""";

In [18]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a) Check missing values
print("Missing Values in Each Column:")
print(df.isnull().sum())

# b) Fill missing Price values with the column mean
df["Price"] = df["Price"].fillna(df["Price"].mean())

print("\nDataFrame after filling missing Price:")
print(df)

# c) Drop rows where Stock is missing
df = df.dropna(subset=["Stock"])

print("\nDataFrame after dropping missing Stock:")
print(df)

# d) Save the cleaned DataFrame to CSV
df.to_csv("cleaned_products.csv", index=False)

print("\nData saved successfully to 'cleaned_products.csv'")

Missing Values in Each Column:
Product    0
Price      2
Stock      1
dtype: int64

DataFrame after filling missing Price:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

DataFrame after dropping missing Stock:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

Data saved successfully to 'cleaned_products.csv'


In [19]:
"""
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:

a) Print its shape and column names.

b) Add a new column Total_Value as Price multiplied by Stock.

c) Use describe() to print summary statistics of the numeric columns.

d) Wrap the file reading step in
a try-except block to handle the case where the file does not exist (FileNotFoundError).
""";

In [20]:
import pandas as pd

try:
    # Read the CSV file
    df = pd.read_csv("cleaned_products.csv")

    # a) Print shape and column names
    print("Shape of DataFrame:", df.shape)
    print("Column Names:", list(df.columns))

    # b) Add a new column Total_Value
    df["Total_Value"] = df["Price"] * df["Stock"]

    print("\nDataFrame with Total_Value:")
    print(df)

    # c) Display summary statistics
    print("\nSummary Statistics:")
    print(df.describe())

except FileNotFoundError:
    print("Error: 'cleaned_products.csv' file not found. Please create the file first.")

Shape of DataFrame: (4, 3)
Column Names: ['Product', 'Price', 'Stock']

DataFrame with Total_Value:
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary Statistics:
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
